import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { publicConfig } from './config.js';

/**
 * A benchmark result that cannot be reproduced is an anecdote. Every writer
 * here emits the full configuration and metadata alongside the numbers, and
 * the caveats travel with the data rather than living in a README nobody
 * opens.
 */

export const CAVEATS = [
  'Simulated clients do not render the world and carry no client-side cost. Real players at the same count are heavier, so a player count derived from this tool is a CEILING, not a promise.',
  'Bots wander on a script. Real players cluster, build, fight and idle in ways this does not reproduce.',
  "With sampling.method='time', TPS is inferred from the server's 20-tick time-sync packet. It is a coarse average and cannot see per-tick spikes; MSPT is unavailable.",
  'With RCON, TPS samples are one-minute rolling averages; MSPT samples are five-second rolling averages/minima/maxima. MSPT mean averages those window means; MSPT max is the largest observed window maximum. Neither is a per-tick percentile.',
  'Results are pinned to the server software, version and hardware recorded in metadata. They go stale when any of those change.',
];

function fmt(n, unit = '') {
  return n === null || n === undefined ? '—' : `${n}${unit}`;
}

export function toMarkdown(result) {
  const m = result.metadata || {};
  const lines = [];
  lines.push(`# Minecraft server benchmark${m.label ? ` — ${m.label}` : ''}`);
  lines.push('');
  lines.push(`**Run:** ${result.startedAt} → ${result.finishedAt}`);
  lines.push('');

  const spec = [
    ['Server software', m.serverSoftware],
    ['Server version', m.serverVersion],
    ['Java', m.javaVersion],
    ['Plan RAM', m.planRamGb ? `${m.planRamGb} GB` : ''],
    ['Plan CPU', m.planCpuPercent ? `${m.planCpuPercent}%` : ''],
    ['Hardware', m.hardware],
    ['Sampling', result.config.sampling.method],
    ['Hold / settle', `${result.config.holdSeconds}s / ${result.config.settleSeconds}s`],
    ['Movement', result.config.bots.move ? `on, spread ${result.config.bots.spreadRadius}m` : 'OFF'],
  ].filter(([, v]) => v);
  if (spec.length) {
    lines.push('| Setting | Value |', '|---|---|');
    for (const [k, v] of spec) lines.push(`| ${k} | ${v} |`);
    lines.push('');
  }

  const hasMspt = result.steps.some((s) => s.mspt);
  lines.push(
    hasMspt
      ? '| Players | Joined | Moving | TPS mean | TPS p5 | TPS min | MSPT mean | MSPT max | TPS / MSPT samples |'
      : '| Players | Joined | Moving | TPS mean | TPS p5 | TPS min | Samples |',
  );
  lines.push(hasMspt ? '|---:|---:|---:|---:|---:|---:|---:|---:|---:|' : '|---:|---:|---:|---:|---:|---:|---:|');
  for (const s of result.steps) {
    const base = `| ${s.target} | ${s.joined} | ${s.moving} | ${fmt(s.tps.mean)} | ${fmt(s.tps.p5)} | ${fmt(s.tps.min)} |`;
    lines.push(hasMspt
      ? `${base} ${fmt(s.mspt?.mean, 'ms')} | ${fmt(s.mspt?.max, 'ms')} | ${s.tpsSamples} / ${s.msptSamples} |`
      : `${base} ${s.samples} |`);
  }
  lines.push('');

  if (result.headline) {
    lines.push(`**Read:** ${result.headline}`, '');
  }

  lines.push('## Caveats', '');
  for (const c of CAVEATS) lines.push(`- ${c}`);
  lines.push('');
  lines.push('Generated by mctickrate — run it yourself against any server.');
  return lines.join('\n');
}

export function toCsv(result) {
  const head = 'players,joined,moving,tps_mean,tps_p5,tps_min,tps_p50,mspt_mean,mspt_max,samples,tps_samples,mspt_samples';
  const rows = result.steps.map((s) => [
    s.target, s.joined, s.moving,
    s.tps.mean ?? '', s.tps.p5 ?? '', s.tps.min ?? '', s.tps.p50 ?? '',
    s.mspt?.mean ?? '', s.mspt?.max ?? '', s.samples, s.tpsSamples, s.msptSamples,
  ].join(','));
  return [head, ...rows].join('\n');
}

/** A server is "comfortable" while its 5th-percentile TPS holds at or above this. */
export const COMFORT_TPS_P5 = 19.5;

/**
 * The one sentence a reader actually wants: where does it stop being fine?
 * "Comfortable" is TPS p5 >= 19.5 — using the 5th percentile rather than the
 * mean, because a server that averages 20 and dips to 12 is not comfortable.
 */
export function headline(steps) {
  const withData = steps.filter((s) => s.tps.p5 !== null);
  if (!withData.length) return 'No TPS samples captured — check the sampling configuration.';

  // ONE threshold, so there is no gap between "comfortable" and "degraded".
  // Using p5 rather than the mean: a server averaging 20 that dips to 12 is
  // not comfortable, and the dip is what players notice.
  const firstDipIdx = withData.findIndex((s) => s.tps.p5 < COMFORT_TPS_P5);

  if (firstDipIdx === 0) {
    return `Below ${COMFORT_TPS_P5} TPS (p5) from the very first step (${withData[0].target} players) `
      + '— start the ramp lower.';
  }
  if (firstDipIdx === -1) {
    return `Held ≥${COMFORT_TPS_P5} TPS (p5) at every tested count, up to `
      + `${withData.at(-1).target} players — the ceiling is above this ramp, so test higher.`;
  }

  const dip = withData[firstDipIdx];
  const lastGood = withData[firstDipIdx - 1].target;

  // A ramp is not guaranteed to fall monotonically. If a LATER step recovers
  // above the line, the dip was probably noise rather than a wall, and
  // reporting it as a ceiling would be wrong — an earlier version of this
  // emitted the self-contradicting "held to 60; first dip at 50".
  const recovered = withData
    .slice(firstDipIdx + 1)
    .filter((s) => s.tps.p5 >= COMFORT_TPS_P5)
    .map((s) => s.target);

  if (recovered.length) {
    return `Inconclusive: dipped below ${COMFORT_TPS_P5} TPS (p5) at ${dip.target} players `
      + `(p5 ${dip.tps.p5}) but recovered at ${recovered.join(', ')}. The curve is not `
      + 'monotonic, so this is measurement noise rather than a ceiling — repeat the run, '
      + 'hold each step longer, or narrow the ramp around that range.';
  }
  return `Held ≥${COMFORT_TPS_P5} TPS (p5) to ${lastGood} players; degrades from `
    + `${dip.target} (p5 ${dip.tps.p5}).`;
}

export function write(result, cfg) {
  mkdirSync(cfg.output.dir, { recursive: true });
  const stamp = result.startedAt.replace(/[:.]/g, '-');
  const base = join(cfg.output.dir, `mctickrate-${stamp}`);
  const written = [];
  if (cfg.output.formats.includes('json')) {
    writeFileSync(`${base}.json`, JSON.stringify({ ...result, config: publicConfig(result.config) }, null, 2));
    written.push(`${base}.json`);
  }
  if (cfg.output.formats.includes('markdown')) {
    writeFileSync(`${base}.md`, toMarkdown(result));
    written.push(`${base}.md`);
  }
  if (cfg.output.formats.includes('csv')) {
    writeFileSync(`${base}.csv`, toCsv(result));
    written.push(`${base}.csv`);
  }
  return written;
}
